apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: testworld
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: local/world:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: testworld
  labels:
    app: helloworld
  spec:
    selector:
      app.kubernetes.io/name: helloworld
    ports:
    - protocol: TCP
      port: 9000
      targetPort: 80