apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: hw
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: local/helloworld:dev
          ports:
            - containerPort: 8080