apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: mycluster
image: rancher/k3s:v1.24.13-k3s1
servers: 1
agents: 2
ports:
  - port: 8081:8081
    nodeFilters:
      - loadbalancer
registries:
  create: 
    name: myregistry
  config: |
    mirrors:
      "my.company.registry":
        endpoint:
          - http://localhost:8081
